import { Inter, Exo_2 } from 'next/font/google';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });
const exo2 = Exo_2({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'Next.js Application',
  description: 'Generated by Next.js with custom font and SEO enhancements',
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  openGraph: {
    title: 'Next.js Application',
    description: 'Generated by Next.js with custom font and SEO enhancements',
    url: 'https://your-app.com',
    siteName: 'Next.js App',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Next.js Application',
      },
    ],
    locale: 'en-US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Next.js Application',
    description: 'Generated by Next.js with custom font and SEO enhancements',
    images: ['/twitter-image.jpg'],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} ${exo2.className}`}>
      <body>{children}</body>
    </html>
  );
}